export enum CryptoActionsType {
  GET_CRYPTOS = 'GET_CRYPTOS',
  GET_CRYPTOS_SUCCESS = 'GET_CRYPTOS_SUCCESS',
  GET_CRYPTOS_ERROR = 'GET_CRYPTOS_ERROR',

  ADD_CRYPTOS = 'ADD_CRYPTOS',
  ADD_CRYPTOS_SUCCESS = 'ADD_CRYPTOS_SUCCESS',
  ADD_CRYPTOS_ERROR = 'ADD_CRYPTOS_ERROR',
}
